### ISSUE TITLE
Regelung präzisieren: Laser _immer_ beaufsichtigen

### ISSUE THREAD

**Issue by ReneDens** [fau-fablab/lasercutter-einweisung#12]
Sonderregel für unbrennbare Materialien auf Seite 1 et al. entfernen.
Ersetzen durch: Laser muss im Betrieb immer mit Blick in den Arbeitsraum beaufsichtigt werden.

**Comment by mgmax** [comment]
Wieso?

**Comment by ReneDens** [comment]
Weil der neue Lasercutter wohl genug Fehlerpotential hat, wohl auch ohne Material lustige Dinge zutun um die unumstössliche Regel, dass Maschinen immer beaufsichtigt werden müssen, auch weiterhin durchzusetzen.
Es gibt keinen sinnvollen Grund nicht zu sagen "Der Laser muss immer beaufsichtigt werden."...
Bei den 3D-Druckern ist nur die Weinerei ob der stundenlangen Druckzeit ein Grund ein Auge zuzudrücken, aber beim Laser zieht dieses Argument null. Punktum.
Desweiteren sind einfache Regeln besser als komplexe Regeln mit Ausnahmen.

**Comment by mgmax** [comment]
Nur damit alles einheitlich und einfach ist eine Regel einzuführen ist so eine Sache, auch wenn ich die Gefahr von Missverständnissen durchaus sehe.
Hintergedanke war z.B. wenn man eine große Steinplatte gravieren will. Dann haben wir eine ähnliche Argumentation wie bei den 3D-Druckern. Mit deinem Vorschlag müsste man dann entweder sinnlos dabeistehen oder -- noch schlimmer -- die Regel ignorieren, daher möchte ich es nicht einfach streichen.
Ich erstelle in Kürze einen Vorschlag, wie man es in eine Fußnote entsorgt und damit die wichtigsten Probleme loswird.
