### ISSUE TITLE
Formatierung geändert

### ISSUE THREAD

**Issue by tweinreich** [fau-fablab/lasercutter-einweisung#3]
Seite 18:
![bildschirmfoto 2015-06-23 um 18 49 04](https://cloud.githubusercontent.com/assets/4059641/8311746/a0194c76-19d8-11e5-929d-b26f62d8a538.png)

Der Fließtext geht auf Seite 18 nicht weiter, sondern ab da wird eine Bullet-List erstellt.

**Comment by gr7ffo** [comment]
Danke für deinen Input! :+1:

**Comment by tweinreich** [comment]
Bitte :-)
